# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_auto_20170720_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='in_print',
            field=models.BooleanField(verbose_name=True),
        ),
    ]
